services:
  #Database
  public_db:
    image: mariadb:11.3.2
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3335:3306
    restart: always
    env_file: .env
    environment:
      MARIADB_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
      MARIADB_DATABASE: wordpress
    container_name: public_db
  #Web
  public_wp:
    depends_on:
      - public_db
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - 8101:80
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: public_db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: psd_
      WORDPRESS_CONFIG_EXTRA: |
        define( 'JETPACK_SIGNATURE__HTTPS_PORT', 0 );
        define( 'MEDIA_TRASH', true );
        define( 'EMPTY_TRASH_DAYS', 30); 
        define( 'PP_EDIT_EXCEPTIONS_ALLOW_ATTACHMENT_DELETION', true );
        define( 'DISALLOW_FILE_EDIT', true);
        define( 'WPCF7_ADMIN_READ_CAPABILITY', 'manage_options' );
        define( 'WPCF7_ADMIN_READ_WRITE_CAPABILITY', 'manage_options' );
    container_name: public_wp
    volumes:
      - ./wp-content:/var/www/html/wp-content
  #PhpMyAdmin
  public_myadmin:
    image: phpmyadmin:latest
    container_name: public_myadmin
    restart: "no"
    ports:
      - 5021:80
    environment:
      PMA_HOST: public_db
      UPLOAD_LIMIT: 1000M
    depends_on:
      - public_db
volumes:
  db_data:
  wp-content:
